name: Tata
favicon: null
layout_spectrum: 0.76303
typography_spectrum: 0.06764
title: Vlogi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0d5cd'
    - '#030200'
    - '#212c16'
    - '#a79e98'
    - '#4d5c29'
  brandStrength: 0.125
  lightness: 0.717046971898526
  saturation: 0.5093394825235009
  rhythmicContrast: 0.3401193923782557
purpose: []
