name: Tata
favicon: null
layout_spectrum: 0.76303
typography_spectrum: 0.06764
title: Vlogi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050706'
    - '#f9f9f9'
    - '#4a4e56'
    - '#ee754b'
    - '#e2a595'
  brandStrength: 0.5
  lightness: 0.717046971898526
  saturation: 0.5093394825235009
  rhythmicContrast: 0.3401193923782557
purpose: []
